zeo:
  build: zeo
  hostname: zeo
  expose:
   - "8100"
  volumes:
   - ~/tmp/filestorage:/buildout/var/filestorage
   - ~/tmp/blobstorage:/buildout/var/blobstorage
instance1:
  build: instance
  hostname: instance1
  links:
   - zeo:zeo
  expose:
   - "8080"
  volumes_from:
   - zeo
instance2:
  build: instance
  hostname: instance2
  links:
   - zeo:zeo
  expose:
   - "8080"
  volumes_from:
   - zeo
varnish:
  build: varnish
  links:
   - instance1:instance1
   - instance2:instance2
  ports:
   - "80:6081"
