from       ju55i/plonebase
MAINTAINER Jussi Talaskivi <jptalask@gmail.com>

workdir	/usr/local/zope
volume	/site
add	buildout.cfg /usr/local/zope/
run	su zope -c "buildout"
cmd	su zope -c "./bin/zeoserver fg"

expose	8100
